create table users(
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null,

    primary key (id)
);