create table user_sessions(
    id bigint generated by default as identity,
    valid boolean not null,
    created_at timestamp not null,
    expires_at timestamp not null,
    user_id bigint not null,

    primary key (id),

    constraint fk_user foreign key (user_id) references users(id) on delete cascade
);