create table refresh_tokens(
    id bigint generated by default as identity,
    token_value varchar(255) not null unique,
    issued_at timestamp not null,
    used boolean not null,
    session_id bigint not null,
    version int,

    primary key (id),

    constraint fk_user_session foreign key (session_id) references user_sessions(id) on delete cascade
);