create table products(
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    description text,
    stock int not null,
    price numeric not null,
    created_at timestamptz not null,
    created_by varchar(255) not null,
    modified_at timestamptz,
    modified_by varchar(255),
    version int,

    primary key (id)
);