name: Application tests

on:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Load project
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Create JWT encryption keys
        run: |
          mkdir -p src/main/resources/security/jwt
          openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out src/main/resources/security/jwt/jwt_private_key.pem -outpubkey src/main/resources/security/jwt/jwt_public_key.pem

      - name: Run tests
        run: ./mvnw verify -B